# Generated by Django 3.1 on 2020-09-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='new_item',
            field=models.BooleanField(default=True),
        ),
    ]
